spring:
  application:
    name: auth-service
  datasource:
#    TODO : maybe create profile for testing
#    url: jdbc:postgresql://localhost:5432/vehicle_fleet tests
    url: jdbc:postgresql://host.docker.internal:5432/vehicle_fleet
    username: postgres
    password: PostgresPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
