server:
  port:8090

spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:postgresql://db:5432/vehicle_fleet
    username: postgres
    password: PostgresPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

auth-service:
  base-url: http://auth-service
